language: objective-c
install:
  - brew remove --force xctool
  - brew install xctool --HEAD

script:
   - xctool test -workspace Example/HNKServerFacade-Example.xcworkspace -scheme HNKServerFacade-Example -sdk iphonesimulator8.1
