language: objective-c
install:
  - brew remove --force xctool
  - brew install xctool --HEAD

script:
   - xctool test -project Example/HNKServerFacade-Example.xcodeproj -scheme HNKServerFacade-Example -sdk iphonesimulator8.1
